/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Monorepo {
  usePackStructure?: boolean
  packages?: Array<PhyrePackage>
}

export interface PhyrePackage {
  name: string
  prefix: string
}

export declare function routeScanner(config?: Monorepo | undefined | null): void
